"""Schema version constants for runtime-domain payloads."""

SCHEMA_RUNTIME_SUMMARY = "runtime_summary.v1"
SCHEMA_RUNTIME_CYCLE_LIST = "runtime_cycle_list.v1"
SCHEMA_RUNTIME_RUN_PAPER = "runtime_run_paper.v1"
SCHEMA_RUNTIME_REPLAY_REPORT = "runtime_replay_report.v1"
SCHEMA_RUNTIME_EVIDENCE_RECORD = "runtime_evidence_record.v1"
SCHEMA_RUNTIME_PIPELINE_RESULT = "runtime_pipeline_result.v1"
SCHEMA_EXECUTION_APPROVAL = "execution_approval.v1"
SCHEMA_ALPHA_BUDGET_USAGE = "alpha_budget_usage.v1"
SCHEMA_ALPHA_BUDGET_USAGE_REPORT = "alpha_budget_usage_report.v1"
SCHEMA_ENGINE_STATUS = "engine_status.v1"
SCHEMA_CLI_ERROR = "cli_error.v1"
SCHEMA_ALPHA_BATCH_EVALUATION = "alpha_batch_evaluation.v1"
SCHEMA_ALPHA_RUNTIME_INGESTION = "alpha_runtime_ingestion.v1"
