"""PositionClosed event — immutable, single-authority close record.

FIX-20260611-005 Phase 2: Event sourcing adapter for position close events.
PositionCloseAdapter is the ONLY component that generates these events.
Journal is an append-only projection of this event stream.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PositionClosed:
    """Immutable record of a position close (or partial close).

    Generated by PositionCloseAdapter from MT5 DEAL data.
    Each DEAL that reduces net position by > tick_size generates one event.
    """

    position_ticket: int
    symbol: str
    side: str  # "long" | "short"
    strategy: str
    magic: int

    # ── Trade data (MUST be > 0) ──
    entry_price: float
    close_price: float
    closed_volume: float  # this partial close volume
    remaining_volume: float  # volume still open after this close
    original_volume: float  # total position volume at open

    pnl: float

    # ── Exit metadata ──
    label: str  # canonical: sl_hit_first, tp_hit_first, win, loss, breakeven, etc.
    position_identifier: int = 0  # DQAF-033: MT5 immutable anchor — POSITION_IDENTIFIER
    exit_reason: str = ""  # raw reason string from deal / engine
    close_time: str = ""  # ISO UTC
    source: str = ""  # "mt5_deal" | "engine_close"

    # ── Attribution ──
    brain_ids: tuple[str, ...] = ()
    trail_contribution: dict | None = None
    open_message_id: str = ""

    # ── Technical ──
    message_id: str = ""
    deal_id: int = 0  # MT5 deal ID for dedup
    sl: float = 0.0
    tp: float = 0.0
    recorded_at: str = ""

    def to_journal_entry(self) -> dict:
        """Convert to live_trade_journal.v2 format."""
        return {
            "schema_version": "live_trade_journal.v2",
            "recorded_at": self.recorded_at,
            "message_id": self.message_id or f"close_{self.position_ticket}_{self.deal_id}",
            "target": "exec_bridge",
            "ack_status": "closed",
            "detail": {
                "reason": self.exit_reason,
                "close_price": self.close_price,
                "pnl": self.pnl,
                "deal_id": self.deal_id,
            },
            "symbol": self.symbol,
            "action": "close",
            "side": self.side,
            "volume": self.closed_volume,
            "pnl": self.pnl,
            "label": self.label,
            "position_ticket": self.position_ticket,
            "position_identifier": self.position_identifier or self.position_ticket,
            "magic": self.magic,
            "strategy": self.strategy,
            "sl": self.sl,
            "tp": self.tp,
            "open_message_id": self.open_message_id,
            "brain_ids": list(self.brain_ids) if self.brain_ids else None,
            "trail_contribution": self.trail_contribution,
            "entry_price": self.entry_price,
            "exit_price": self.close_price,
        }


@dataclass(frozen=True)
class PositionOpened:
    """Immutable record of a position open.

    Generated when MT5 confirms the order and position_manager registers it.
    """

    position_ticket: int
    symbol: str
    side: str  # "long" | "short"
    strategy: str
    magic: int
    entry_price: float  # MUST be > 0
    volume: float  # MUST be > 0
    sl: float = 0.0
    tp: float = 0.0
    brain_ids: tuple[str, ...] = ()
    brain_votes: tuple = ()
    confidence: float = 0.0
    p_win: float = 0.5
    p_win_source: str = "unknown"
    p_win_degraded: bool = False
    kelly_mult: float = 1.0
    entry_context: dict | None = None
    message_id: str = ""
    recorded_at: str = ""

    def to_journal_entry(self) -> dict:
        """Convert to live_trade_journal.v2 format (open action)."""
        return {
            "schema_version": "live_trade_journal.v2",
            "recorded_at": self.recorded_at,
            "message_id": self.message_id,
            "target": "exec_bridge",
            "ack_status": "accepted",
            "symbol": self.symbol,
            "action": "open",
            "side": self.side,
            "volume": self.volume,
            "pnl": None,
            "label": None,
            "position_ticket": self.position_ticket,
            "magic": self.magic,
            "strategy": self.strategy,
            "entry_price": self.entry_price,
            "sl": self.sl,
            "tp": self.tp,
            "brain_ids": list(self.brain_ids) if self.brain_ids else None,
            "brain_votes": list(self.brain_votes) if self.brain_votes else None,
            "confidence": self.confidence,
            "p_win": self.p_win,
            "p_win_source": self.p_win_source,
            "p_win_degraded": self.p_win_degraded,
            "kelly_mult": self.kelly_mult,
            "entry_context": self.entry_context,
            "effective_volume_hint": self.volume,
            "execution_payload_schema": "live_mt5_execution_payload.v2",
        }
